; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
lib_deps =
    vshymanskyy/TinyGSM @ ^0.11.7
    bblanchon/ArduinoJson @ ^7.3.0
    arduino-libraries/ArduinoHttpClient @ ^0.6.1
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DTINY_GSM_MODEM_SIM7000
    -DTINY_GSM_RX_BUFFER=1024
    -DARDUINO_USB_CDC_ON_BOOT=1
